---
- name: Install and check httpd package
  hosts: webservers
  gather_facts: true
  tasks:
  - name: Check httpd installed and up to date 
    ansible.builtin.dnf:
      name: httpd
      state: latest
  
  - name: Ensure httpd is running
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
